# Generated by Django 5.0.6 on 2024-06-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("price1", models.FloatField()),
                ("description", models.TextField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("G", "Generic"),
                            ("E", "Electronics"),
                            ("F", "Fashion"),
                            ("H&F", "Home and Furnitures"),
                            ("B&H", "Beauty and Health"),
                            ("B&M", "Books and Media"),
                            ("S&O", "Sports and Outdoor"),
                            ("T&B", "Toys and Baby Products"),
                            ("F&B", "Food and Beverages"),
                        ],
                        default="G",
                        max_length=3,
                    ),
                ),
                ("image", models.CharField(max_length=250)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
