# Generated by Django 5.0.6 on 2024-06-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purplegorilla", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
